version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
    ports:
      - "3306:3306"
    # app:
    #   build:
    #     context: .
    #     dockerfile: Dockerfile
    #   environment:
    #     DB_USER: root
    #     DB_PASSWORD: root_password
    #     DB_ADDRESS: db:3306
    #     DB_NAME: ecommerce
    #   ports:
    #     - "8080:8080"
    # depends_on:
    #   - db
